name: bluebird_app
description: App de login y registro con tema Bluebird Soft

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase Core (requerido)
  firebase_core: ^4.1.0
  cloud_functions: ^6.0.1
  # Firebase Services que necesites:
  firebase_auth: ^6.0.2          # Autenticación
  cloud_firestore: ^6.0.1        # Base de datos
  firebase_storage: ^13.0.1       # Almacenamiento
  firebase_messaging: ^16.0.1    # Push notifications
  google_sign_in: ^6.0.1       # Google Sign-In 
  
  cupertino_icons: ^1.0.2
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
   

  